name: Build
on: [push]
jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: Running the code
              run: node node.mjs
              working-directory: ./res